### ISSUE TITLE
wireframes for cms

### ISSUE THREAD

**Issue by carlpeaslee** [artsmia/knight#10]
I've been working through the cms a bit and I think it will be easier if I create some mockups first. Will put together a sketch file.

**Comment by carlpeaslee** [comment]
Let's post links / screen shots of cms we like here.

**Comment by carlpeaslee** [comment]
Gretchen noted this: https://storymap.knightlab.com/gigapixel/

**Comment by mtongen** [comment]
Submittable is essentially a fancy form builder, but the layout is nice and offers a good range of file uploads. Instead of screenshots, here's a demo video that walks through the different views: https://www.submittable.com/getting-started-with-submittable
