### ISSUE TITLE
IIIF Compatible Leaflet React Component 

### ISSUE THREAD

**Issue by carlpeaslee** [artsmia/knight#5]
This is a useful implementation –– unfortunately uses jquery... Might still be useful. 

https://github.com/mejackreed/Leaflet-IIIF

**Comment by carlpeaslee** [comment]
Played around with Leaflet-IIIF, just doesn't really seem compatible. Probably easiest to roll our own extension of the tile layer like with museumTileLayer

**Comment by kjell** [comment]
Yes, for now. Our images aren't in IIIF format yet.

Once they are, moving to IIIF will let us reference images from other institutions as well as our own.

[Wikipedia is looking into implementing a IIIF server](https://phabricator.wikimedia.org/T89552)
[along with quite a few other museums](https://docs.google.com/document/d/1UtgKqs_Uy8shm6ErhMaecu1HeCS3wDpeEGD79Z88byg)

**Comment by carlpeaslee** [comment]
relevant implementations on other MIA sites

https://github.com/artsmia/museumTileLayer
https://github.com/artsmia/griot-electron-prototype/blob/master/components/viewer.js
